### ISSUE TITLE
nodecore not fully syncing?

### ISSUE THREAD

**Issue by mrheat** [VeriBlock/nodecore-releases#127]
Hi

i got a problem where wallet is not syncing any further than block 87624..
i deleted blocks dat file to force redownloading but again im stuck,
i already checked that i run latest version, what could i try?

**Comment by beursstarter** [comment]
Are you sure you are running the latest version (0.4.4)? This issue is fixed in 0.4.4.
https://github.com/VeriBlock/nodecore-releases/releases/tag/v0.4.4

Instead of deleting nodecore.dat and a complete resync you can also use this bootstraps by the way: http://mirror1.veriblock.org/nodecore-bootstrap-89000.zip

**Comment by Leonardiae** [comment]
Are you sure you are running the latest version (0.4.4)? This issue is fixed in 0.4.4.
https://github.com/VeriBlock/nodecore-releases/releases/tag/v0.4.4

Instead of deleting nodecore.dat and a complete resync you can also use this bootstraps by the way: http://mirror1.veriblock.org/nodecore-bootstrap-89000.zip
